version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: custom-pokemon-service
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app  

volumes:
  mongo-data:
